# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b90b3929ad914835675ca4ac4e8c34d7976420d519e01dc5039d71f4bd8adb630178e1c505b3d2123394eb5d65a77436fa9fdd0ec4d53ad67f8aa9f7dbb11e06

test:
  secret_key_base: 1df53a6736cfdd0d73ebae273099bc3aee80bdae6190ca12093078ccd99c7e511818f9329e2ee5c07d970ed5dc185cbc97b2b54afa47861379e0b922418c6b48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
